version: "3.9"
services:
  nginx:
    ports:
      - "443:443"
      - "80:80"
      - "3537:3537"
      - "3030:3030"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    image: nginx
    restart: unless-stopped
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - needs-network
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    networks:
      - needs-network
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  needs-network:
    name: needs_network
    external: true
